# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts

$wallDIR=$HOME/Pictures/wallpapers
$lock = $scriptsDir/LockScreen.sh
$SwwwRandom = $UserScripts/WallpaperAutoChange.sh
$livewallpaper="$HOME/Pictures/wallpapers/GIF/bepis-wallpaperwaifu-com.mp4"

# wallpaper stuff 
exec-once = swww-daemon --format xrgb
#exec-once = mpvpaper '*' -o "load-scripts=no no-audio --loop" $livewallpaper

# Dynamic wallpaper — changes by time of day
exec-once = sleep 2 && $scriptsDir/DynamicWallpaper.sh loop

# Startup
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Polkit (Polkit Gnome / KDE)
exec-once = $scriptsDir/Polkit.sh

# starup apps
exec-once = nm-applet --indicator
exec-once = swaync
exec-once = blueman-applet
#exec-once = rog-control-center
exec-once = waybar
#exec-once = qs # quickshell AGS Desktop Overview alternative
#exec-once = ags run ~/.config/ags/app.tsx

#clipboard manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Rainbow borders
#exec-once = $UserScripts/RainbowBorders.sh

# Starting hypridle to start hyprlock
exec-once = hypridle

# Hyprland event listener (workspace sounds, etc.)
exec-once = $scriptsDir/HyprEvents.sh


# Here are list of features available but disabled by default
# exec-once = swww-daemon --format xrgb && swww img $HOME/Pictures/wallpapers/mecha-nostalgia.png  # persistent wallpaper

#gnome polkit for nixos
#exec-once = $scriptsDir/Polkit-NixOS.sh

# xdg-desktop-portal-hyprland (should be auto starting. However, you can force to start)
#exec-once = $scriptsDir/PortalHyprland.sh
