# Portal 2 / Aperture Science — Decoration Settings

source = $HOME/.config/hypr/wallust/wallust-hyprland.conf

general {
  border_size = 2
  gaps_in = 3
  gaps_out = 6

  col.active_border = $color12
  col.inactive_border = $color10
}

decoration {
  rounding = 8
  rounding_power = 1

  active_opacity = 0.90
  inactive_opacity = 0.0   # GUI почти невидим — остаётся только акриловое размытие
  fullscreen_opacity = 1.0

  dim_inactive = false      # не затемнять — контент и так скрыт
  dim_strength = 0.08
  dim_special = 0.6

  shadow {
    enabled = true
    range = 120
    render_power = 2
    color = rgba(00a1e420)
    color_inactive = rgba(0d0e1a40)
  }

  blur {
    enabled = true
    size = 10
    passes = 3
    ignore_opacity = true
    new_optimizations = true
    special = true
    popups = true
    noise = 0.015
    contrast = 1.05
    brightness = 0.92
    vibrancy = 0.2
    vibrancy_darkness = 0.3
  }
}

group {
  col.border_active = $color4

  groupbar {
    col.active = $color1
  }
}
