# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FEF5F2
background         #010007
cursor             #ADA6B5

active_tab_foreground     #010007
active_tab_background     #FEF5F2
inactive_tab_foreground   #FEF5F2
inactive_tab_background   #010007

active_border_color   #FEF5F2
inactive_border_color #010007
bell_border_color     #2E293B

color0      #010007
color1		#2E293B
color2		#45425A
color3		#686689
color4		#6C6B8E
color5		#6C6B8E
color6		#BEAAA3
color7		#F6E9E4
color8		#ACA39F
color9		#3D374F
color10		#5C5878
color11		#8B89B6
color12		#908EBD
color13		#908EBD
color14		#FDE3D9
color15		#F6E9E4
