# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(010007)
$foreground = rgb(FEF5F2)
$color0 = rgb(010007)
$color1 = rgb(2E293B)
$color2 = rgb(45425A)
$color3 = rgb(686689)
$color4 = rgb(6C6B8E)
$color5 = rgb(6C6B8E)
$color6 = rgb(BEAAA3)
$color7 = rgb(F6E9E4)
$color8 = rgb(ACA39F)
$color9 = rgb(3D374F)
$color10 = rgb(5C5878)
$color11 = rgb(8B89B6)
$color12 = rgb(908EBD)
$color13 = rgb(908EBD)
$color14 = rgb(FDE3D9)
$color15 = rgb(F6E9E4)
